### ISSUE TITLE
Firefox 117 generated faulty HAR with the bidi exporter

### ISSUE THREAD

**Issue by soulgalore** [firefox-devtools/bidi-har-export#19]
Hi,
one of my test cases stopped to work updating to Firefox 117.

Dropping it into har viewer gives me this:
<img width="583" alt="Screenshot 2023-09-01 at 07 20 39" src="https://github.com/firefox-devtools/bidi-har-export/assets/540757/7b7fa961-3ab3-48e3-9038-ac03fe1854af">

And looking in the HAR headers looks like this (checkout the type):
```
"entries": [
      {
        "request": {
          "bodySize": null,
          "method": "GET",
          "url": "https://en.wikipedia.org/wiki/Main_Page",
          "httpVersion": "h2",
          "headers": [
            {
              "name": "Host",
              "value": {"type": "string", "value": "en.wikipedia.org"}
            },
            {
              "name": "User-Agent",
              "value": {
                "type": "string",
                "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
              }
            },
            {
              "name": "Accept",
              "value": {
                "type": "string",
                "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
              }
            },
...
```
This didn't happen with 116.

Attaching an example HAR. 

[browsertime.har.zip](https://github.com/firefox-devtools/bidi-har-export/files/12494630/browsertime.har.zip)

**Comment by juliandescottes** [comment]
Ah thanks for the heads up we did a non backward compatible change on the
network events, around the headers and cookies format.

I can put up a patch later today, sorry about this!

**Comment by juliandescottes** [comment]
@soulgalore let me know how pressing this is. The fix in #20 is straightforward, so if needed I can publish the version early. Otherwise I'll wait for review from peers.

Thanks

**Comment by soulgalore** [comment]
Thanks @juliandescottes that would be great, then I can roll out tests on Firefox 117 :)

**Comment by juliandescottes** [comment]
I thought I commented already, but @soulgalore you can try v0.0.12, it should fix the issue hopefully (but should still work with older Firefox versions)

**Comment by soulgalore** [comment]
Thank you @juliandescottes for fixing this so fast! :)
