### ISSUE TITLE
0.0.15 broke timings in Browsertime

### ISSUE THREAD

**Issue by soulgalore** [firefox-devtools/bidi-har-export#32]
I was going through some tests today at it looks that at least Firefox 131.0  and the fix for the timings do not work somehow (they are in minutes). I created an issue https://github.com/sitespeedio/browsertime/issues/2189 with an example HAR file. So I just updated to the version but maybe I need to do a code fix?

**Comment by juliandescottes** [comment]
Oh yes you're right, the code is completely wrong when it tries to update the intermediary timings 🤦 
I will fix it soon.

**Comment by juliandescottes** [comment]
@soulgalore can you try v0.0.16 and let me know if it fixes the issue?

**Comment by soulgalore** [comment]
Thank you that fixed the problem!
